version: "3.7"
services:
  quarkus:
    depends_on:
      - postgres
    build:
      context: "."
    ports:
      - "8080:8080"
    environment:
      QUARKUS_DATASOURCE_URl: jdbc:postgresql://postgres:5432/postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
